### ISSUE TITLE
ML components of DDoSGrid

### ISSUE THREAD

**Issue by tvdhout** [ddosgrid/ddosgrid-v2#2]
Hi! I am working on the [ddos_dissector](https://github.com/ddos-clearing-house/ddos_dissector) and I was wondering where I could find the machine learning aspects of DDoS Grid as presented in [Luc Boillat's Thesis](https://files.ifi.uzh.ch/CSG/staff/franco/extern/theses/MA-L-Boillat.pdf). I would like to see if I could implement something similar for the ddos_dissector. I did not find any machine learning components in this repository; is this code publicly available? If so, could someone point me in the right direction? Thanks!

**Comment by tvdhout** [comment]
Ah -- I believe I found it in one of the tags in this repo: https://github.com/ddosgrid/ddosgrid-v2/releases/tag/ml-1.1

**Comment by jvdassen** [comment]
Hi Thijs,

Yes, you're right. The ML components are not yet merged with the main branch (`master`), the development of said ML components is done on the `ml` branch.

**Comment by jvdassen** [comment]
BTW, the feature extraction (which I'm assuming you're trying to replicate in the dissector) for said ML components happens inside of the `miner` component in [miner/miners/MachineLearningFeatureExtraction.js](https://github.com/ddosgrid/ddosgrid-v2/blob/ml/miner/miners/MachineLearningFeatureExtraction.js).
