### ISSUE TITLE
Allow rebasing for `flow` team

### ISSUE THREAD

**Issue by ChristianBirchler** [ddosgrid/ddosgrid-v2#3]
As a developer of the `flow` team, I want to be able to do rebasing for having a cleaner Git history.

If I do some rebasing locally then I change the Git history. When I want to push the changes my push gets rejected since I am not allowed to change the Git history on the remote. I think there is a branch protection rule enabled. Is it possible to change this or shall we just keep the development with merge commits instead of rebasing?

**Comment by jvdassen** [comment]
Yeah I can see why this is desirable and having no merge commits would certainly be nice :-)
Just to be sure, are you doing a force push to the remote branch (e.g. `git push origin flowxyz -f`)?
Or is your remote branch fast-forwardable but it still doesnt work?
